/**
 * The starting exercise library, added the first time the library is read
 * (services/training/exerciseService.js). `seedKey` never changes: it is how seeding stays
 * idempotent and how a gym's edits to these exercises survive restarts.
 *
 * [seedKey, name, primaryMuscle, secondaryMuscles, equipment, category, instructions]
 */
const ROWS = [
  // Chest
  ['barbell-bench-press', 'Barbell bench press', 'chest', ['triceps', 'shoulders'], 'barbell', 'strength',
    'Lie on the bench with eyes under the bar and feet flat. Lower the bar to mid-chest with elbows about 45° from the body, then press up until the arms are straight.'],
  ['incline-barbell-bench-press', 'Incline barbell bench press', 'chest', ['shoulders', 'triceps'], 'barbell', 'strength',
    'Set the bench to 30–45°. Lower the bar to the upper chest under control and press it back up over the shoulders.'],
  ['dumbbell-bench-press', 'Dumbbell bench press', 'chest', ['triceps', 'shoulders'], 'dumbbell', 'strength',
    'Lie flat holding the dumbbells at chest level. Press them up until they nearly touch, then lower slowly until you feel a stretch in the chest.'],
  ['incline-dumbbell-press', 'Incline dumbbell press', 'chest', ['shoulders', 'triceps'], 'dumbbell', 'strength',
    'Set the bench to 30–45°. Press the dumbbells up over the upper chest and lower them slowly to the sides of the chest.'],
  ['dumbbell-fly', 'Dumbbell fly', 'chest', ['shoulders'], 'dumbbell', 'strength',
    'Lie flat with the dumbbells above the chest and a slight bend in the elbows. Open the arms wide until you feel a stretch, then bring them back together in an arc.'],
  ['cable-crossover', 'Cable crossover', 'chest', ['shoulders'], 'cable', 'strength',
    'Stand between the pulleys with one foot forward. Pull the handles down and together in front of the chest, pause, and return slowly.'],
  ['push-up', 'Push-up', 'chest', ['triceps', 'shoulders', 'core'], 'bodyweight', 'strength',
    'Hands slightly wider than the shoulders, body in one straight line. Lower the chest close to the floor and push back up without letting the hips sag. Do them on the knees or against a bench to make them easier.'],
  ['chest-press-machine', 'Chest press machine', 'chest', ['triceps', 'shoulders'], 'machine', 'strength',
    'Set the seat so the handles are at mid-chest. Press forward until the arms are straight, then return slowly without letting the weight stack touch.'],
  ['pec-deck-fly', 'Pec deck fly', 'chest', ['shoulders'], 'machine', 'strength',
    'Sit tall with the back against the pad. Bring the handles together in front of the chest, squeeze, and open slowly.'],

  // Back
  ['deadlift', 'Deadlift', 'back', ['hamstrings', 'glutes', 'forearms'], 'barbell', 'strength',
    'Stand with the bar over mid-foot. Hinge down, grip just outside the knees, flatten the back and brace. Push the floor away and stand up tall, keeping the bar close to the legs.'],
  ['pull-up', 'Pull-up', 'back', ['biceps', 'forearms'], 'bodyweight', 'strength',
    'Hang with hands a little wider than the shoulders. Pull the chest toward the bar by driving the elbows down, then lower all the way. Use the assisted machine or a band if needed.'],
  ['lat-pulldown', 'Lat pulldown', 'back', ['biceps'], 'cable', 'strength',
    'Sit with thighs under the pads and grip the bar wide. Pull it to the upper chest while leaning back slightly, then let it rise slowly.'],
  ['seated-cable-row', 'Seated cable row', 'back', ['biceps'], 'cable', 'strength',
    'Sit tall with knees slightly bent. Pull the handle to the stomach, squeeze the shoulder blades together, and return without rounding the back.'],
  ['barbell-row', 'Barbell bent-over row', 'back', ['biceps', 'forearms'], 'barbell', 'strength',
    'Hinge forward with a flat back, bar hanging below the shoulders. Pull the bar to the lower chest and lower it under control.'],
  ['one-arm-dumbbell-row', 'One-arm dumbbell row', 'back', ['biceps'], 'dumbbell', 'strength',
    'Put one hand and knee on a bench. Pull the dumbbell to the hip with the elbow close to the body, then lower it fully.'],
  ['straight-arm-pulldown', 'Straight-arm pulldown', 'back', ['core'], 'cable', 'strength',
    'Stand facing a high pulley with arms straight. Sweep the bar down to the thighs using the back, not the arms, then let it rise slowly.'],
  ['back-extension', 'Back extension', 'back', ['glutes', 'hamstrings'], 'bodyweight', 'strength',
    'Set the pad just below the hips. Lower the upper body with a flat back, then rise until the body is in a straight line. Do not swing past straight.'],
  ['barbell-shrug', 'Barbell shrug', 'back', ['forearms'], 'barbell', 'strength',
    'Hold the bar in front of the thighs with straight arms. Lift the shoulders toward the ears, pause, and lower. Do not roll the shoulders.'],

  // Shoulders
  ['overhead-press', 'Overhead barbell press', 'shoulders', ['triceps', 'core'], 'barbell', 'strength',
    'Stand with the bar on the front of the shoulders. Brace the core and press the bar straight overhead, moving the head back slightly as it passes.'],
  ['seated-dumbbell-press', 'Seated dumbbell shoulder press', 'shoulders', ['triceps'], 'dumbbell', 'strength',
    'Sit with back support, dumbbells at ear height. Press up until the arms are straight and lower back to ear height.'],
  ['lateral-raise', 'Lateral raise', 'shoulders', [], 'dumbbell', 'strength',
    'Stand with dumbbells at your sides. Raise the arms out to shoulder height with a slight bend in the elbows, then lower slowly. Keep the weight light.'],
  ['front-raise', 'Front raise', 'shoulders', [], 'dumbbell', 'strength',
    'Raise the dumbbells in front of you to shoulder height with straight arms, then lower slowly without swinging.'],
  ['rear-delt-fly', 'Rear delt fly', 'shoulders', ['back'], 'dumbbell', 'strength',
    'Hinge forward with a flat back. Raise the dumbbells out to the sides, leading with the elbows, and squeeze the upper back.'],
  ['face-pull', 'Face pull', 'shoulders', ['back'], 'cable', 'strength',
    'Set a rope at face height. Pull it toward the forehead with elbows high, pulling the rope ends apart, then return slowly.'],
  ['shoulder-press-machine', 'Shoulder press machine', 'shoulders', ['triceps'], 'machine', 'strength',
    'Set the seat so the handles start at shoulder height. Press up until the arms are straight and lower under control.'],

  // Arms
  ['barbell-curl', 'Barbell curl', 'biceps', ['forearms'], 'barbell', 'strength',
    'Stand with elbows at your sides. Curl the bar to the shoulders without swinging the body, then lower it all the way.'],
  ['dumbbell-curl', 'Dumbbell curl', 'biceps', ['forearms'], 'dumbbell', 'strength',
    'Curl the dumbbells up, turning the palms to face you, and lower slowly. Keep the elbows still.'],
  ['hammer-curl', 'Hammer curl', 'biceps', ['forearms'], 'dumbbell', 'strength',
    'Hold the dumbbells with palms facing each other. Curl up without turning the wrists and lower slowly.'],
  ['preacher-curl', 'Preacher curl', 'biceps', [], 'barbell', 'strength',
    'Rest the upper arms on the preacher pad. Curl the bar up and lower it until the arms are almost straight.'],
  ['triceps-pushdown', 'Triceps pushdown', 'triceps', [], 'cable', 'strength',
    'Face a high pulley with elbows tucked at your sides. Push the bar or rope down until the arms are straight, then let it rise to chest height.'],
  ['overhead-triceps-extension', 'Overhead triceps extension', 'triceps', [], 'dumbbell', 'strength',
    'Hold one dumbbell overhead with both hands. Lower it behind the head by bending the elbows, then straighten the arms.'],
  ['skull-crusher', 'Skull crusher', 'triceps', [], 'barbell', 'strength',
    'Lie on a bench holding an EZ bar over the chest. Bend the elbows to lower the bar toward the forehead, then straighten the arms.'],
  ['bench-dip', 'Bench dip', 'triceps', ['chest', 'shoulders'], 'bodyweight', 'strength',
    'Hands on the edge of a bench behind you, legs out in front. Lower until the elbows are at 90° and push back up.'],
  ['close-grip-bench-press', 'Close-grip bench press', 'triceps', ['chest'], 'barbell', 'strength',
    'Grip the bar about shoulder-width apart. Lower it to the lower chest with elbows close to the body and press up.'],

  // Legs
  ['back-squat', 'Barbell back squat', 'quads', ['glutes', 'hamstrings', 'core'], 'barbell', 'strength',
    'Bar on the upper back, feet shoulder-width apart. Brace, sit down between the heels until the thighs are at least parallel, and stand up. Keep the knees in line with the toes.'],
  ['front-squat', 'Front squat', 'quads', ['glutes', 'core'], 'barbell', 'strength',
    'Rest the bar on the front of the shoulders with elbows high. Squat down keeping the chest up, then stand.'],
  ['goblet-squat', 'Goblet squat', 'quads', ['glutes', 'core'], 'kettlebell', 'strength',
    'Hold a kettlebell or dumbbell at the chest. Squat down between the heels with the chest up, then stand. A good first squat for beginners.'],
  ['leg-press', 'Leg press', 'quads', ['glutes', 'hamstrings'], 'machine', 'strength',
    'Feet shoulder-width on the platform. Lower until the knees reach about 90° without the lower back lifting off the pad, then press up. Do not lock the knees.'],
  ['romanian-deadlift', 'Romanian deadlift', 'hamstrings', ['glutes', 'back'], 'barbell', 'strength',
    'Stand holding the bar. Push the hips back with a slight knee bend, sliding the bar down the thighs until you feel the hamstrings stretch, then stand up.'],
  ['walking-lunge', 'Walking lunge', 'quads', ['glutes', 'hamstrings'], 'dumbbell', 'strength',
    'Step forward and lower until both knees are bent about 90°. Push through the front heel and step into the next lunge.'],
  ['bulgarian-split-squat', 'Bulgarian split squat', 'quads', ['glutes'], 'dumbbell', 'strength',
    'Rest the back foot on a bench. Lower straight down on the front leg until the thigh is near parallel, then push up.'],
  ['leg-extension', 'Leg extension', 'quads', [], 'machine', 'strength',
    'Sit with the pad on the lower shins. Straighten the legs, pause, and lower slowly.'],
  ['lying-leg-curl', 'Lying leg curl', 'hamstrings', [], 'machine', 'strength',
    'Lie face down with the pad above the heels. Curl the heels toward the glutes and lower slowly.'],
  ['hip-thrust', 'Barbell hip thrust', 'glutes', ['hamstrings'], 'barbell', 'strength',
    'Upper back on a bench, bar over the hips with a pad. Drive the hips up until the body is flat from knees to shoulders, squeeze, and lower.'],
  ['glute-bridge', 'Glute bridge', 'glutes', ['hamstrings', 'core'], 'bodyweight', 'strength',
    'Lie on your back with knees bent. Push through the heels to lift the hips, squeeze the glutes at the top, and lower.'],
  ['step-up', 'Step-up', 'quads', ['glutes'], 'dumbbell', 'strength',
    'Step onto a sturdy box or bench with one foot and stand up fully on it. Step down with control and repeat.'],
  ['standing-calf-raise', 'Standing calf raise', 'calves', [], 'machine', 'strength',
    'Balls of the feet on the edge of the platform. Rise up as high as you can, pause, and lower the heels below the platform.'],
  ['seated-calf-raise', 'Seated calf raise', 'calves', [], 'machine', 'strength',
    'Sit with the pad on the thighs and balls of the feet on the platform. Raise the heels, pause, and lower fully.'],

  // Core
  ['plank', 'Plank', 'core', ['shoulders'], 'bodyweight', 'strength',
    'Forearms under the shoulders, body in a straight line from head to heels. Brace the stomach and hold. Log the seconds held as reps.'],
  ['side-plank', 'Side plank', 'core', [], 'bodyweight', 'strength',
    'Lie on one side on the forearm and lift the hips so the body is straight. Hold, then switch sides. Log seconds as reps.'],
  ['crunch', 'Crunch', 'core', [], 'bodyweight', 'strength',
    'Lie with knees bent. Curl the shoulders off the floor using the stomach, not the neck, and lower slowly.'],
  ['hanging-leg-raise', 'Hanging leg raise', 'core', ['forearms'], 'bodyweight', 'strength',
    'Hang from a bar. Raise the legs (bent or straight) to hip height or higher without swinging, then lower slowly.'],
  ['russian-twist', 'Russian twist', 'core', [], 'bodyweight', 'strength',
    'Sit leaning back slightly with feet on or off the floor. Rotate the chest side to side. Hold a plate to make it harder.'],
  ['cable-crunch', 'Cable crunch', 'core', [], 'cable', 'strength',
    'Kneel facing a high pulley holding a rope by the head. Crunch down by curling the spine and return slowly.'],
  ['ab-wheel-rollout', 'Ab wheel rollout', 'core', ['shoulders'], 'other', 'strength',
    'Kneel holding the wheel. Roll forward as far as you can with a flat back, then pull back with the stomach.'],
  ['mountain-climber', 'Mountain climber', 'core', ['shoulders', 'quads'], 'bodyweight', 'cardio',
    'Start in a push-up position. Drive the knees toward the chest one after the other at a steady, fast pace.'],

  // Full body and conditioning
  ['kettlebell-swing', 'Kettlebell swing', 'glutes', ['hamstrings', 'back', 'core'], 'kettlebell', 'strength',
    'Hinge at the hips and hike the kettlebell back between the legs, then snap the hips forward to swing it to chest height. The power comes from the hips, not the arms.'],
  ['burpee', 'Burpee', 'full_body', ['chest', 'quads'], 'bodyweight', 'cardio',
    'Squat, place the hands down, jump the feet back to a plank, jump them back in, and jump up. Step instead of jumping to make it easier.'],
  ['farmers-walk', "Farmer's walk", 'forearms', ['back', 'core'], 'dumbbell', 'strength',
    'Hold heavy dumbbells at your sides, stand tall, and walk with short, steady steps. Log the distance or seconds as reps.'],
  ['band-pull-apart', 'Band pull-apart', 'shoulders', ['back'], 'band', 'strength',
    'Hold a band in front of you at shoulder height. Pull it apart until it touches the chest, squeezing the shoulder blades, and return slowly.'],

  // Cardio
  ['treadmill', 'Treadmill walk or run', 'full_body', [], 'cardio_machine', 'cardio',
    'Start with a 3–5 minute easy walk, then set the speed or incline for the session. Log the minutes as reps.'],
  ['stationary-bike', 'Stationary bike', 'quads', ['calves'], 'cardio_machine', 'cardio',
    'Set the seat so the knee is slightly bent at the bottom of the pedal stroke. Keep a steady pace. Log the minutes as reps.'],
  ['cross-trainer', 'Cross trainer', 'full_body', [], 'cardio_machine', 'cardio',
    'Stand tall, hold the moving handles and push and pull with the arms while pedalling. Log the minutes as reps.'],
  ['rowing-machine', 'Rowing machine', 'back', ['quads', 'core'], 'cardio_machine', 'cardio',
    'Push with the legs first, then lean back slightly and pull the handle to the lower ribs. Return in the reverse order. Log the minutes as reps.'],
  ['skipping', 'Skipping rope', 'calves', ['shoulders'], 'other', 'cardio',
    'Jump just high enough to clear the rope, landing softly on the balls of the feet. Log the minutes as reps.'],

  // Mobility and stretching
  ['cat-cow', 'Cat-cow', 'back', ['core'], 'bodyweight', 'mobility',
    'On hands and knees, round the back up toward the ceiling, then let the stomach drop and lift the chest. Move slowly with the breath.'],
  ['worlds-greatest-stretch', "World's greatest stretch", 'full_body', ['hamstrings', 'glutes'], 'bodyweight', 'mobility',
    'Step into a deep lunge, place both hands inside the front foot, then rotate the chest and reach one arm to the ceiling. Switch sides.'],
  ['hip-flexor-stretch', 'Kneeling hip flexor stretch', 'quads', ['glutes'], 'bodyweight', 'stretching',
    'Kneel on one knee with the other foot forward. Squeeze the glute of the back leg and shift forward until you feel a stretch at the front of the hip. Hold 30 seconds per side.'],
  ['hamstring-stretch', 'Hamstring stretch', 'hamstrings', [], 'bodyweight', 'stretching',
    'Sit with one leg straight and reach toward the toes with a flat back until you feel a stretch. Hold 30 seconds per side.'],
  ['doorway-chest-stretch', 'Doorway chest stretch', 'chest', ['shoulders'], 'bodyweight', 'stretching',
    'Place the forearm on a door frame at shoulder height and step through until you feel a stretch across the chest. Hold 30 seconds per side.'],
  ['childs-pose', "Child's pose", 'back', ['shoulders'], 'bodyweight', 'stretching',
    'Kneel, sit back on the heels and reach the arms forward on the floor. Breathe slowly and hold for 30–60 seconds.'],
];

export const EXERCISE_SEED = ROWS.map(([seedKey, name, primaryMuscle, secondaryMuscles, equipment, category, instructions]) => ({
  seedKey,
  name,
  primaryMuscle,
  secondaryMuscles,
  equipment,
  category,
  instructions,
}));
